ALTER TABLE document ADD COLUMN IF NOT EXISTS graph_status VARCHAR(32) NOT NULL DEFAULT 'PENDING';
ALTER TABLE document ADD COLUMN IF NOT EXISTS graph_progress INTEGER NOT NULL DEFAULT 0;
ALTER TABLE document ADD COLUMN IF NOT EXISTS graph_error TEXT;
ALTER TABLE document ADD COLUMN IF NOT EXISTS graph_node_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE document ADD COLUMN IF NOT EXISTS graph_relation_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE document ADD COLUMN IF NOT EXISTS vector_chunk_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE document ADD COLUMN IF NOT EXISTS graph_synced_at TIMESTAMPTZ;
