<script setup lang="ts">
import { onMounted,reactive,ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage,ElMessageBox } from 'element-plus'
import { ArrowLeft,Delete,Edit,Plus,Search } from '@element-plus/icons-vue'
import { createDictionary,deleteDictionary,listDictionary,updateDictionary,type DictionaryInput,type GeologicalDictionary } from '@/api/documents'
const router=useRouter(),loading=ref(false),items=ref<GeologicalDictionary[]>([]),query=ref(''),type=ref(''),dialog=ref(false),editing=ref<number>(),form=reactive<DictionaryInput>({termType:'LITHOLOGY',standardName:'',aliases:'',description:'',enabled:true})
const types=[['STRATUM','地层'],['LITHOLOGY','岩性'],['ROCK_BODY','岩体'],['FAULT','断裂'],['MINERAL','矿种'],['ORE_BODY','矿体'],['MINERALIZATION_ZONE','矿化带'],['GEOLOGICAL_AGE','地质年代'],['PLACE','地名']]
async function load(){loading.value=true;try{items.value=await listDictionary({query:query.value||undefined,type:type.value||undefined})}catch(e){ElMessage.error(msg(e))}finally{loading.value=false}}
function open(item?:GeologicalDictionary){editing.value=item?.id;Object.assign(form,item?{termType:item.termType,standardName:item.standardName,aliases:item.aliases||'',description:item.description||'',enabled:item.enabled}:{termType:'LITHOLOGY',standardName:'',aliases:'',description:'',enabled:true});dialog.value=true}
async function save(){if(!form.standardName.trim())return ElMessage.warning('请输入标准名称');try{editing.value?await updateDictionary(editing.value,form):await createDictionary(form);dialog.value=false;ElMessage.success('词典条目已保存');await load()}catch(e){ElMessage.error(msg(e))}}
async function remove(item:GeologicalDictionary){try{await ElMessageBox.confirm(`删除词典条目“${item.standardName}”？`,'删除确认',{type:'warning'});await deleteDictionary(item.id);ElMessage.success('已删除');await load()}catch(e){if(e!=='cancel')ElMessage.error(msg(e))}}
function label(v:string){return types.find(i=>i[0]===v)?.[1]||v} function msg(e:unknown){return e instanceof Error?e.message:'操作失败'}
onMounted(load)
</script>
<template><div class="dictionary-page"><header class="page-intro"><div><button class="back-action" type="button" @click="router.push('/knowledge')"><el-icon><ArrowLeft/></el-icon>返回知识抽取</button><span class="eyebrow">Phase 5 · Geological dictionary</span><h1>地质术语词典</h1><p>维护标准名称和别名集合，为实体保留可追溯的匹配结果。</p></div><button class="primary-action" type="button" @click="open()"><el-icon><Plus/></el-icon>新增术语</button></header><section class="dictionary-toolbar"><el-input v-model="query" clearable placeholder="搜索标准名称或别名" @keyup.enter="load"><template #prefix><el-icon><Search/></el-icon></template></el-input><el-select v-model="type" clearable placeholder="全部类型" @change="load"><el-option v-for="entry in types" :key="entry[0]" :label="entry[1]" :value="entry[0]"/></el-select><button type="button" @click="load">查询</button><small>{{items.length}} 条术语</small></section><section class="dictionary-table" v-loading="loading"><header><span>标准名称</span><span>类型</span><span>别名</span><span>说明</span><span>操作</span></header><article v-for="item in items" :key="item.id"><strong>{{item.standardName}}</strong><span><i>{{label(item.termType)}}</i></span><span>{{item.aliases?.split('|').join('、')||'—'}}</span><span>{{item.description||'—'}}</span><span><button type="button" :aria-label="`编辑 ${item.standardName}`" @click="open(item)"><el-icon><Edit/></el-icon></button><button type="button" :aria-label="`删除 ${item.standardName}`" @click="remove(item)"><el-icon><Delete/></el-icon></button></span></article></section><el-dialog v-model="dialog" :title="editing?'编辑术语':'新增术语'" width="min(520px, 92vw)"><el-form label-position="top"><div class="form-grid"><el-form-item label="术语类型"><el-select v-model="form.termType"><el-option v-for="entry in types" :key="entry[0]" :label="entry[1]" :value="entry[0]"/></el-select></el-form-item><el-form-item label="标准名称"><el-input v-model="form.standardName" maxlength="255"/></el-form-item></div><el-form-item label="别名"><el-input v-model="form.aliases" placeholder="多个别名使用 | 分隔"/></el-form-item><el-form-item label="术语说明"><el-input v-model="form.description" type="textarea" :rows="3"/></el-form-item><el-switch v-model="form.enabled" active-text="启用匹配"/></el-form><template #footer><button class="secondary-action" type="button" @click="dialog=false">取消</button><button class="primary-action" type="button" @click="save">保存术语</button></template></el-dialog></div></template>
