package com.cug.geotext.service;

import com.cug.geotext.common.BusinessException;
import com.cug.geotext.entity.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.util.*;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;

@Service
public class ExportService {
    private final DocumentService documents;private final GeologicalEntityService entities;private final KnowledgePersistenceService knowledge;private final SpatialObjectService spatial;private final ObjectMapper json;
    public ExportService(DocumentService documents,GeologicalEntityService entities,KnowledgePersistenceService knowledge,SpatialObjectService spatial,ObjectMapper json){this.documents=documents;this.entities=entities;this.knowledge=knowledge;this.spatial=spatial;this.json=json;}
    public ExportFile export(long documentId,String format,String dataset){GeologicalDocument document=documents.get(documentId);List<GeologicalEntity>entityRows=entities.list(documentId);List<EntityAttribute>attributes=knowledge.attributes(documentId);List<EntityRelation>relations=knowledge.relations(documentId);List<SpatialObject>objects=spatial.list(documentId);String base=safe(document.getName());return switch(format.toLowerCase()){case "xlsx"->new ExportFile(base+"-成果.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",excel(entityRows,attributes,relations,objects));case "json"->new ExportFile(base+"-成果.json","application/json",json(document,entityRows,attributes,relations,objects));case "geojson"->new ExportFile(base+"-空间对象.geojson","application/geo+json",geojson(objects));case "csv"->new ExportFile(base+"-"+dataset+".csv","text/csv",csv(dataset,entityRows,attributes,relations,objects));default->throw new BusinessException(400,"导出格式仅支持 xlsx、csv、json、geojson");};}
    private byte[] excel(List<GeologicalEntity>e,List<EntityAttribute>a,List<EntityRelation>r,List<SpatialObject>s){try(Workbook wb=new XSSFWorkbook();ByteArrayOutputStream out=new ByteArrayOutputStream()){sheet(wb,"实体",List.of("ID","名称","标准名称","类型","置信度","页码","原文"),e.stream().map(x->List.of(x.getId(),x.getEntityName(),value(x.getStandardName()),x.getEntityType(),x.getConfidence(),x.getPage(),x.getSourceText())).toList());sheet(wb,"属性",List.of("ID","实体ID","属性类型","值","置信度","页码","原文"),a.stream().map(x->List.of(x.getId(),x.getEntityId(),x.getAttributeType(),x.getOriginalValue(),x.getConfidence(),x.getPage(),x.getSourceText())).toList());sheet(wb,"关系",List.of("ID","源实体ID","目标实体ID","关系类型","置信度","页码","原文"),r.stream().map(x->List.of(x.getId(),x.getSourceEntityId(),x.getTargetEntityId(),x.getRelationType(),x.getConfidence(),x.getPage(),x.getSourceText())).toList());sheet(wb,"空间对象",List.of("ID","名称","类型","几何","经度","纬度","页码","原文"),s.stream().map(x->List.of(x.getId(),x.getName(),x.getObjectType(),x.getGeojson(),x.getCenterLongitude(),x.getCenterLatitude(),x.getPage(),x.getSourceText())).toList());wb.write(out);return out.toByteArray();}catch(Exception ex){throw new BusinessException(500,"Excel 导出失败: "+ex.getMessage());}}
    private void sheet(Workbook wb,String name,List<String>headers,List<? extends List<?>>rows){Sheet sheet=wb.createSheet(name);Row header=sheet.createRow(0);CellStyle style=wb.createCellStyle();Font font=wb.createFont();font.setBold(true);style.setFont(font);for(int i=0;i<headers.size();i++){Cell cell=header.createCell(i);cell.setCellValue(headers.get(i));cell.setCellStyle(style);}for(int i=0;i<rows.size();i++){Row row=sheet.createRow(i+1);for(int j=0;j<rows.get(i).size();j++)row.createCell(j).setCellValue(String.valueOf(rows.get(i).get(j)));}for(int i=0;i<headers.size();i++)sheet.setColumnWidth(i,Math.min(i==headers.size()-1?16000:6000,255*256));}
    private byte[] json(GeologicalDocument d,List<GeologicalEntity>e,List<EntityAttribute>a,List<EntityRelation>r,List<SpatialObject>s){try{return json.writerWithDefaultPrettyPrinter().writeValueAsBytes(Map.of("document",d,"entities",e,"attributes",a,"relations",r,"spatialObjects",s));}catch(Exception ex){throw new BusinessException(500,"JSON 导出失败");}}
    private byte[] geojson(List<SpatialObject>objects){try{ObjectNode root=json.createObjectNode();root.put("type","FeatureCollection");ArrayNode features=root.putArray("features");for(SpatialObject object:objects){ObjectNode feature=features.addObject();feature.put("type","Feature");feature.set("geometry",json.readTree(object.getGeojson()));ObjectNode properties=feature.putObject("properties");properties.put("id",object.getId());properties.put("name",object.getName());properties.put("objectType",object.getObjectType());properties.put("documentName",object.getDocumentName());properties.put("page",object.getPage());properties.put("sourceText",object.getSourceText());properties.put("confidence",object.getConfidence());}return json.writerWithDefaultPrettyPrinter().writeValueAsBytes(root);}catch(Exception ex){throw new BusinessException(500,"GeoJSON 导出失败");}}
    private byte[] csv(String dataset,List<GeologicalEntity>e,List<EntityAttribute>a,List<EntityRelation>r,List<SpatialObject>s){List<? extends List<?>>rows;List<?>header;switch(dataset==null?"entities":dataset){case "attributes"-> {header=List.of("id","entityId","attributeType","value","confidence","page","sourceText");rows=a.stream().map(x->List.of(x.getId(),x.getEntityId(),x.getAttributeType(),x.getOriginalValue(),x.getConfidence(),x.getPage(),x.getSourceText())).toList();}case "relations"->{header=List.of("id","sourceEntityId","targetEntityId","relationType","confidence","page","sourceText");rows=r.stream().map(x->List.of(x.getId(),x.getSourceEntityId(),x.getTargetEntityId(),x.getRelationType(),x.getConfidence(),x.getPage(),x.getSourceText())).toList();}case "spatial"->{header=List.of("id","name","objectType","geojson","longitude","latitude","page","sourceText");rows=s.stream().map(x->List.of(x.getId(),x.getName(),x.getObjectType(),x.getGeojson(),x.getCenterLongitude(),x.getCenterLatitude(),x.getPage(),x.getSourceText())).toList();}default->{header=List.of("id","name","standardName","entityType","confidence","page","sourceText");rows=e.stream().map(x->List.of(x.getId(),x.getEntityName(),value(x.getStandardName()),x.getEntityType(),x.getConfidence(),x.getPage(),x.getSourceText())).toList();}}StringBuilder out=new StringBuilder("\ufeff");append(out,header);for(List<?>row:rows)append(out,row);return out.toString().getBytes(StandardCharsets.UTF_8);}
    private void append(StringBuilder out,List<?>row){out.append(row.stream().map(v->"\""+String.valueOf(v).replace("\"","\"\"")+"\"").reduce((a,b)->a+","+b).orElse("")).append("\r\n");}private String value(String v){return v==null?"":v;}private String safe(String name){return name.replaceAll("[\\\\/:*?\"<>|]","_");}
    public record ExportFile(String filename,String contentType,byte[] content){}
}
